---
title: 'fsMCMC, using Non-centered simulation-based proposals for intractable likelihoods'
output:
  pdf_document: default
  html_notebook: default
---

Observing the evolution of an infectious disease may be limited by many factors. In some cases, it may only be feasible to observe a subset of the population at discrete time points. This makes inference difficult, as it is not possible to build a tractable likelihood as we only have partial observation of the epidemic. 

A large number of MCMC methods assumed that calculation of the posterior (upto a constant of proportionality) is possible, including the ones used previously in this series. This requires calculation of the likelihood, which is not possible in the epidemic panel data case.

MCMC still possible with an unbiased estimate of the likelihood (Psuedo-Marginal MCMC) in place of the analytical expression.

How do we get this estimate for the likelihood in our case?

Using simulations of an epidemic, it is possible to recieve a realisation of the epidemic.

```{latex}
$\lambda$
```
# Gillespie Simulation



```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
