# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calling_c <- function(x, y) {
    .Call('_Epidemics_calling_c', PACKAGE = 'Epidemics', x, y)
}

concat <- function(x, y) {
    .Call('_Epidemics_concat', PACKAGE = 'Epidemics', x, y)
}

event_epidemicsC <- function(individual_inf_rate, gamma, Y, U) {
    .Call('_Epidemics_event_epidemicsC', PACKAGE = 'Epidemics', individual_inf_rate, gamma, Y, U)
}

prod_part_infC <- function(inf_times, rem_times, B, log = TRUE) {
    .Call('_Epidemics_prod_part_infC', PACKAGE = 'Epidemics', inf_times, rem_times, B, log)
}

